[package]
name = "clarirs-smtrs"
version = "0.1.0"
edition = "2024"
description = "smtrs solver backend for clarirs"
license = { workspace = true }
readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
repository = { workspace = true }

[dependencies]
clarirs-core = { path = "../clarirs-core" }
clarirs-num = { path = "../clarirs-num" }
smtrs-core = { workspace = true }
smtrs-solver = { workspace = true }
smallvec = "1"

[lints]
workspace = true
