"""Type stubs for ``angr.rustylib.claripy.ast.base``."""

from collections.abc import Sequence
from typing import Any, Self

from angr.rustylib.claripy.annotation import Annotation
from angr.rustylib.claripy.ast.fp import RM, FSort

# What ``Base.args`` can hold: child ASTs, plus the leaf values and op
# parameters that are not ASTs (names, widths, extract bounds, concrete
# values, and the float sort/rounding mode of the FP ops).
type ArgType = Base | int | float | bool | str | FSort | RM

class Base:
    @property
    def name(self) -> str | None: ...
    @property
    def _encoded_name(self) -> bytes | None: ...
    @property
    def op(self) -> str: ...
    @property
    def args(self) -> list[ArgType]: ...
    @property
    def variables(self) -> frozenset[str]: ...
    @property
    def symbolic(self) -> bool: ...
    @property
    def concrete(self) -> bool: ...
    # Implemented once here, dispatching on the AST type. The sort-specific subclasses narrow the
    # return type rather than reimplementing it: a BV only ever wraps a bitvector AST, and so on.
    @property
    def concrete_value(self) -> bool | int | float | str | None: ...
    @property
    def annotations(self) -> list[Annotation]: ...
    @property
    def depth(self) -> int: ...
    def hash(self) -> int: ...
    def __hash__(self) -> int: ...
    def shallow_repr(self, max_depth: int = 2) -> str: ...
    def canonicalize(
        self, var_map: dict[int, Base] | None = None, counter: Any | None = None
    ) -> tuple[dict[int, Base], Any, Self]: ...
    def identical(self, other: Base) -> bool: ...
    def is_leaf(self) -> bool: ...
    def simplify(self, respect_annotations: bool = True) -> Self: ...
    def replace(self, from_: Base, to: Base, /) -> Self: ...
    def has_annotation_type(self, annotation_type: type[Annotation]) -> bool: ...
    def get_annotations_by_type(self, annotation_type: type[Annotation]) -> list[Annotation]: ...
    def get_annotation(self, annotation_type: type[Annotation]) -> Annotation | None: ...
    def append_annotation(self, annotation: Annotation) -> Self: ...
    def append_annotations(self, annotations: Sequence[Annotation]) -> Self: ...
    def annotate(self, *annotations: Annotation, remove_annotations: Sequence[Annotation] | None = None) -> Self: ...
    def insert_annotations(self, annotations: Sequence[Annotation]) -> Self: ...
    def replace_annotations(self, annotations: Sequence[Annotation]) -> Self: ...
    def remove_annotation(self, annotation: Annotation) -> Self: ...
    def remove_annotations(self, annotations: Sequence[Annotation]) -> Self: ...
    def clear_annotations(self) -> Self: ...
    def clear_annotation_type(self, annotation_type: type[Annotation]) -> Self: ...

__all__ = ["ArgType", "Base"]
