"""Type stubs for ``angr.rustylib.claripy`` -- the claripy API built from
the vendored clarirs sources.

The canonical module paths are ``angr.rustylib.claripy.*``;
``angr/__init__.py`` additionally aliases the whole tree as
``angr.claripy.*`` in ``sys.modules``. There is deliberately no top-level
``claripy`` module.

Everything here is re-exported from the canonical submodules
(``ast.base``, ``ast.bool``, ``ast.bv``, ``ast.fp``, ``ast.strings``,
``annotation``, ``solver``, ``vsa``, ``errors``) except for the handful
of functions that only exist at the top level (``Neq``, ``simplify``,
``replace``, ``excavate_ite``, ``is_true``, ``is_false``).
"""

from . import annotation, ast, errors, fp, solver, vsa
from .annotation import (
    Annotation,
    RegionAnnotation,
    SimplificationAvoidanceAnnotation,
    StridedIntervalAnnotation,
    UninitializedAnnotation,
)
from .ast.base import Base
from .ast.bits import Bits
from .ast.bool import (
    And,
    Bool,
    BoolS,
    BoolV,
    If,
    Not,
    Or,
    false,
    ite_cases,
    ite_dict,
    reverse_ite_cases,
    true,
    xor,
)
from .ast.bv import (
    BV,
    BVS,
    BVV,
    ESI,
    SGE,
    SGT,
    SI,
    SLE,
    SLT,
    UGE,
    UGT,
    ULE,
    ULT,
    VS,
    Add,
    AShR,
    Concat,
    Eq_,
    Extract,
    LShR,
    Mul,
    Reverse,
    RotateLeft,
    RotateRight,
    SDiv,
    ShL,
    SignExt,
    SMod,
    Sub,
    UDiv,
    UMod,
    ZeroExt,
    intersection,
    union,
    widen,
)
from .ast.fp import (
    FP,
    FPS,
    FPV,
    FSORT_DOUBLE,
    FSORT_FLOAT,
    fpAbs,
    fpAdd,
    fpDiv,
    fpEQ,
    fpFP,
    fpGEQ,
    fpGT,
    fpIsInf,
    fpIsNaN,
    fpLEQ,
    fpLT,
    fpMul,
    fpNeg,
    fpNEQ,
    fpSqrt,
    fpSub,
    fpToFP,
    fpToFPUnsigned,
    fpToIEEEBV,
    fpToSBV,
    fpToUBV,
)
from .ast.strings import (
    IntToStr,
    StrConcat,
    StrContains,
    StrEq,
    StrIndexOf,
    String,
    StringS,
    StringV,
    StrIsDigit,
    StrLen,
    StrNeq,
    StrPrefixOf,
    StrReplace,
    StrSubstr,
    StrSuffixOf,
    StrToInt,
)
from .errors import (
    ClaripyError,
    ClaripyFrontendError,
    ClaripyOperationError,
    ClaripySolverInterruptError,
    ClaripyTypeError,
    ClaripyZeroDivisionError,
    InvalidExtractBounds,
    UnsatError,
)
from .solver import (
    Solver,
    SolverCacheless,
    SolverComposite,
    SolverConcrete,
    SolverHybrid,
    SolverReplacement,
    SolverVSA,
    SolverZ3,
)

type _BVLike = BV | int | Bool | bytes | str

def Neq(lhs: _BVLike, rhs: _BVLike) -> Bool: ...
def simplify[T: Base](expr: T) -> T: ...
def replace[T: Base](expr: T, old: Base, new: Base) -> T: ...
def excavate_ite[T: Base](expr: T) -> T: ...
def is_true(expr: object) -> bool:
    """Whether ``expr`` is trivially (concretely) true. Anything that cannot
    be proven true -- including symbolic expressions and non-AST objects --
    yields False."""

def is_false(expr: object) -> bool:
    """Whether ``expr`` is trivially (concretely) false. Anything that cannot
    be proven false yields False."""

__all__ = [
    "BV",
    "BVS",
    "BVV",
    "ESI",
    "FP",
    "FPS",
    "FPV",
    "FSORT_DOUBLE",
    "FSORT_FLOAT",
    "SGE",
    "SGT",
    "SI",
    "SLE",
    "SLT",
    "UGE",
    "UGT",
    "ULE",
    "ULT",
    "VS",
    "AShR",
    "Add",
    "And",
    "Annotation",
    "Base",
    "Bits",
    "Bool",
    "BoolS",
    "BoolV",
    "ClaripyError",
    "ClaripyFrontendError",
    "ClaripyOperationError",
    "ClaripySolverInterruptError",
    "ClaripyTypeError",
    "ClaripyZeroDivisionError",
    "Concat",
    "Eq_",
    "Extract",
    "If",
    "IntToStr",
    "InvalidExtractBounds",
    "LShR",
    "Mul",
    "Neq",
    "Not",
    "Or",
    "RegionAnnotation",
    "Reverse",
    "RotateLeft",
    "RotateRight",
    "SDiv",
    "SMod",
    "ShL",
    "SignExt",
    "SimplificationAvoidanceAnnotation",
    "Solver",
    "SolverCacheless",
    "SolverComposite",
    "SolverConcrete",
    "SolverHybrid",
    "SolverReplacement",
    "SolverVSA",
    "SolverZ3",
    "StrConcat",
    "StrContains",
    "StrEq",
    "StrIndexOf",
    "StrIsDigit",
    "StrLen",
    "StrNeq",
    "StrPrefixOf",
    "StrReplace",
    "StrSubstr",
    "StrSuffixOf",
    "StrToInt",
    "StridedIntervalAnnotation",
    "String",
    "StringS",
    "StringV",
    "Sub",
    "UDiv",
    "UMod",
    "UninitializedAnnotation",
    "UnsatError",
    "ZeroExt",
    "annotation",
    "ast",
    "errors",
    "excavate_ite",
    "false",
    "fp",
    "fpAbs",
    "fpAdd",
    "fpDiv",
    "fpEQ",
    "fpFP",
    "fpGEQ",
    "fpGT",
    "fpIsInf",
    "fpIsNaN",
    "fpLEQ",
    "fpLT",
    "fpMul",
    "fpNEQ",
    "fpNeg",
    "fpSqrt",
    "fpSub",
    "fpToFP",
    "fpToFPUnsigned",
    "fpToIEEEBV",
    "fpToSBV",
    "fpToUBV",
    "intersection",
    "is_false",
    "is_true",
    "ite_cases",
    "ite_dict",
    "replace",
    "reverse_ite_cases",
    "simplify",
    "solver",
    "true",
    "union",
    "vsa",
    "widen",
    "xor",
]
